# Site Information
name: Simple Jekyll Site

description: This is an example Simple Jekyll site.

copyright: Simple Owner

timezone: America/Los_Angeles

# Site Navigation
baseurl: http://herrera-io.github.io/ruby-jekyll-simple/

menu:
  bottom:
    - { label: RSS, url: /blog/feed.xml }
  top:
    - { label: Example, url: / }
    - { label: Portfolio, url: /portfolio/ }
    - { label: Blog, url: /blog/ }

paginate: 100
paginate_path: /blog/page:num

permalink: /blog/:year/:month/:title/

# Post Configuration
disqus: ~

# Markup Configuration
pygments: true

# Content Management
exclude:
  - LICENSE
  - README.md

# Other Settings
safe: true
